// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: acronis_contas.sql

package consultas

import (
	"context"
)

const atualizarAcronisConta = `-- name: AtualizarAcronisConta :one
UPDATE acronis_contas
SET nome = $2, server_url = $3, login = $4, client_id = $5, client_secret = $6, atualizado_em = now()
WHERE id = $1
RETURNING id, nome, server_url, login, client_id, client_secret, criado_em, atualizado_em
`

type AtualizarAcronisContaParams struct {
	ID           int32  `json:"id"`
	Nome         string `json:"nome"`
	ServerUrl    string `json:"server_url"`
	Login        string `json:"login"`
	ClientID     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
}

func (q *Queries) AtualizarAcronisConta(ctx context.Context, arg AtualizarAcronisContaParams) (AcronisConta, error) {
	row := q.db.QueryRow(ctx, atualizarAcronisConta,
		arg.ID,
		arg.Nome,
		arg.ServerUrl,
		arg.Login,
		arg.ClientID,
		arg.ClientSecret,
	)
	var i AcronisConta
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.ServerUrl,
		&i.Login,
		&i.ClientID,
		&i.ClientSecret,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const buscarAcronisConta = `-- name: BuscarAcronisConta :one
SELECT id, nome, server_url, login, client_id, client_secret, criado_em, atualizado_em FROM acronis_contas
WHERE id = $1
`

func (q *Queries) BuscarAcronisConta(ctx context.Context, id int32) (AcronisConta, error) {
	row := q.db.QueryRow(ctx, buscarAcronisConta, id)
	var i AcronisConta
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.ServerUrl,
		&i.Login,
		&i.ClientID,
		&i.ClientSecret,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const criarAcronisConta = `-- name: CriarAcronisConta :one

INSERT INTO acronis_contas (nome, server_url, login, client_id, client_secret)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, nome, server_url, login, client_id, client_secret, criado_em, atualizado_em
`

type CriarAcronisContaParams struct {
	Nome         string `json:"nome"`
	ServerUrl    string `json:"server_url"`
	Login        string `json:"login"`
	ClientID     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
}

// db/queries/acronis_contas.sql
//
// Queries do CRUD de contas Acronis (credenciais OAuth2 client_credentials).
// Parâmetros posicionais ($1, $2…) — sqlc gera prepared statements.
func (q *Queries) CriarAcronisConta(ctx context.Context, arg CriarAcronisContaParams) (AcronisConta, error) {
	row := q.db.QueryRow(ctx, criarAcronisConta,
		arg.Nome,
		arg.ServerUrl,
		arg.Login,
		arg.ClientID,
		arg.ClientSecret,
	)
	var i AcronisConta
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.ServerUrl,
		&i.Login,
		&i.ClientID,
		&i.ClientSecret,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listarAcronisContas = `-- name: ListarAcronisContas :many
SELECT id, nome, server_url, login, client_id, client_secret, criado_em, atualizado_em FROM acronis_contas
ORDER BY id
`

func (q *Queries) ListarAcronisContas(ctx context.Context) ([]AcronisConta, error) {
	rows, err := q.db.Query(ctx, listarAcronisContas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcronisConta{}
	for rows.Next() {
		var i AcronisConta
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.ServerUrl,
			&i.Login,
			&i.ClientID,
			&i.ClientSecret,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removerAcronisConta = `-- name: RemoverAcronisConta :execrows
DELETE FROM acronis_contas
WHERE id = $1
`

func (q *Queries) RemoverAcronisConta(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, removerAcronisConta, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
