// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: filtros.sql

package consultas

import (
	"context"
)

const atualizarFiltro = `-- name: AtualizarFiltro :one
UPDATE filtros
SET alvo = $2, valor = $3, evento = $4, host = $5, atualizado_em = now()
WHERE id = $1
RETURNING id, instancia_id, alvo, valor, evento, host, criado_em, atualizado_em
`

type AtualizarFiltroParams struct {
	ID     int32  `json:"id"`
	Alvo   string `json:"alvo"`
	Valor  string `json:"valor"`
	Evento string `json:"evento"`
	Host   string `json:"host"`
}

func (q *Queries) AtualizarFiltro(ctx context.Context, arg AtualizarFiltroParams) (Filtro, error) {
	row := q.db.QueryRow(ctx, atualizarFiltro,
		arg.ID,
		arg.Alvo,
		arg.Valor,
		arg.Evento,
		arg.Host,
	)
	var i Filtro
	err := row.Scan(
		&i.ID,
		&i.InstanciaID,
		&i.Alvo,
		&i.Valor,
		&i.Evento,
		&i.Host,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const buscarFiltro = `-- name: BuscarFiltro :one
SELECT id, instancia_id, alvo, valor, evento, host, criado_em, atualizado_em FROM filtros
WHERE id = $1
`

func (q *Queries) BuscarFiltro(ctx context.Context, id int32) (Filtro, error) {
	row := q.db.QueryRow(ctx, buscarFiltro, id)
	var i Filtro
	err := row.Scan(
		&i.ID,
		&i.InstanciaID,
		&i.Alvo,
		&i.Valor,
		&i.Evento,
		&i.Host,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const criarFiltro = `-- name: CriarFiltro :one

INSERT INTO filtros (instancia_id, alvo, valor, evento, host)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, instancia_id, alvo, valor, evento, host, criado_em, atualizado_em
`

type CriarFiltroParams struct {
	InstanciaID int32  `json:"instancia_id"`
	Alvo        string `json:"alvo"`
	Valor       string `json:"valor"`
	Evento      string `json:"evento"`
	Host        string `json:"host"`
}

// db/queries/filtros.sql
//
// Queries do CRUD de filtros. Cada filtro pertence a uma instância Zabbix
// (relacionamento 1:N) — ListarFiltrosPorInstancia alimenta o endpoint
// aninhado GET /zabbix/instancias/{id}.
func (q *Queries) CriarFiltro(ctx context.Context, arg CriarFiltroParams) (Filtro, error) {
	row := q.db.QueryRow(ctx, criarFiltro,
		arg.InstanciaID,
		arg.Alvo,
		arg.Valor,
		arg.Evento,
		arg.Host,
	)
	var i Filtro
	err := row.Scan(
		&i.ID,
		&i.InstanciaID,
		&i.Alvo,
		&i.Valor,
		&i.Evento,
		&i.Host,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listarFiltros = `-- name: ListarFiltros :many
SELECT id, instancia_id, alvo, valor, evento, host, criado_em, atualizado_em FROM filtros
ORDER BY id
`

func (q *Queries) ListarFiltros(ctx context.Context) ([]Filtro, error) {
	rows, err := q.db.Query(ctx, listarFiltros)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Filtro{}
	for rows.Next() {
		var i Filtro
		if err := rows.Scan(
			&i.ID,
			&i.InstanciaID,
			&i.Alvo,
			&i.Valor,
			&i.Evento,
			&i.Host,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarFiltrosPorInstancia = `-- name: ListarFiltrosPorInstancia :many
SELECT id, instancia_id, alvo, valor, evento, host, criado_em, atualizado_em FROM filtros
WHERE instancia_id = $1
ORDER BY id
`

func (q *Queries) ListarFiltrosPorInstancia(ctx context.Context, instanciaID int32) ([]Filtro, error) {
	rows, err := q.db.Query(ctx, listarFiltrosPorInstancia, instanciaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Filtro{}
	for rows.Next() {
		var i Filtro
		if err := rows.Scan(
			&i.ID,
			&i.InstanciaID,
			&i.Alvo,
			&i.Valor,
			&i.Evento,
			&i.Host,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removerFiltro = `-- name: RemoverFiltro :execrows
DELETE FROM filtros
WHERE id = $1
`

func (q *Queries) RemoverFiltro(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, removerFiltro, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
