// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package consultas

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcronisConta struct {
	ID           int32              `json:"id"`
	Nome         string             `json:"nome"`
	ServerUrl    string             `json:"server_url"`
	Login        string             `json:"login"`
	ClientID     string             `json:"client_id"`
	ClientSecret string             `json:"client_secret"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}

type Filtro struct {
	ID           int32              `json:"id"`
	InstanciaID  int32              `json:"instancia_id"`
	Alvo         string             `json:"alvo"`
	Valor        string             `json:"valor"`
	Evento       string             `json:"evento"`
	Host         string             `json:"host"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}

type MspInstancia struct {
	ID           int32              `json:"id"`
	ApiKey       string             `json:"api_key"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}

type ZabbixInstancia struct {
	ID           int32              `json:"id"`
	Nome         string             `json:"nome"`
	Url          string             `json:"url"`
	ApiKey       string             `json:"api_key"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}
