// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: msp_instancias.sql

package consultas

import (
	"context"
)

const atualizarMspInstancia = `-- name: AtualizarMspInstancia :one
UPDATE msp_instancias
SET api_key = $2, atualizado_em = now()
WHERE id = $1
RETURNING id, api_key, criado_em, atualizado_em
`

type AtualizarMspInstanciaParams struct {
	ID     int32  `json:"id"`
	ApiKey string `json:"api_key"`
}

func (q *Queries) AtualizarMspInstancia(ctx context.Context, arg AtualizarMspInstanciaParams) (MspInstancia, error) {
	row := q.db.QueryRow(ctx, atualizarMspInstancia, arg.ID, arg.ApiKey)
	var i MspInstancia
	err := row.Scan(
		&i.ID,
		&i.ApiKey,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const buscarMspInstancia = `-- name: BuscarMspInstancia :one
SELECT id, api_key, criado_em, atualizado_em FROM msp_instancias
WHERE id = $1
`

func (q *Queries) BuscarMspInstancia(ctx context.Context, id int32) (MspInstancia, error) {
	row := q.db.QueryRow(ctx, buscarMspInstancia, id)
	var i MspInstancia
	err := row.Scan(
		&i.ID,
		&i.ApiKey,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const criarMspInstancia = `-- name: CriarMspInstancia :one

INSERT INTO msp_instancias (api_key)
VALUES ($1)
RETURNING id, api_key, criado_em, atualizado_em
`

// db/queries/msp_instancias.sql
//
// Queries do CRUD de instâncias MSP Clouds (apenas api_key).
func (q *Queries) CriarMspInstancia(ctx context.Context, apiKey string) (MspInstancia, error) {
	row := q.db.QueryRow(ctx, criarMspInstancia, apiKey)
	var i MspInstancia
	err := row.Scan(
		&i.ID,
		&i.ApiKey,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listarMspInstancias = `-- name: ListarMspInstancias :many
SELECT id, api_key, criado_em, atualizado_em FROM msp_instancias
ORDER BY id
`

func (q *Queries) ListarMspInstancias(ctx context.Context) ([]MspInstancia, error) {
	rows, err := q.db.Query(ctx, listarMspInstancias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MspInstancia{}
	for rows.Next() {
		var i MspInstancia
		if err := rows.Scan(
			&i.ID,
			&i.ApiKey,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removerMspInstancia = `-- name: RemoverMspInstancia :execrows
DELETE FROM msp_instancias
WHERE id = $1
`

func (q *Queries) RemoverMspInstancia(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, removerMspInstancia, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
