// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package consultas

import (
	"context"
)

type Querier interface {
	AtualizarFiltro(ctx context.Context, arg AtualizarFiltroParams) (Filtro, error)
	AtualizarMspInstancia(ctx context.Context, arg AtualizarMspInstanciaParams) (MspInstancia, error)
	AtualizarZabbixInstancia(ctx context.Context, arg AtualizarZabbixInstanciaParams) (ZabbixInstancia, error)
	BuscarFiltro(ctx context.Context, id int32) (Filtro, error)
	BuscarMspInstancia(ctx context.Context, id int32) (MspInstancia, error)
	BuscarZabbixInstancia(ctx context.Context, id int32) (ZabbixInstancia, error)
	// db/queries/filtros.sql
	//
	// Queries do CRUD de filtros. Cada filtro pertence a uma instância Zabbix
	// (relacionamento 1:N) — ListarFiltrosPorInstancia alimenta o endpoint
	// aninhado GET /zabbix/instancias/{id}.
	CriarFiltro(ctx context.Context, arg CriarFiltroParams) (Filtro, error)
	// db/queries/msp_instancias.sql
	//
	// Queries do CRUD de instâncias MSP Clouds (apenas api_key).
	CriarMspInstancia(ctx context.Context, apiKey string) (MspInstancia, error)
	// db/queries/zabbix_instancias.sql
	//
	// Queries do CRUD de instâncias Zabbix. Parâmetros posicionais ($1, $2…)
	// — sqlc gera prepared statements, sem concatenação de string.
	CriarZabbixInstancia(ctx context.Context, arg CriarZabbixInstanciaParams) (ZabbixInstancia, error)
	ListarFiltros(ctx context.Context) ([]Filtro, error)
	ListarFiltrosPorInstancia(ctx context.Context, instanciaID int32) ([]Filtro, error)
	ListarMspInstancias(ctx context.Context) ([]MspInstancia, error)
	ListarZabbixInstancias(ctx context.Context) ([]ZabbixInstancia, error)
	RemoverFiltro(ctx context.Context, id int32) (int64, error)
	RemoverMspInstancia(ctx context.Context, id int32) (int64, error)
	RemoverZabbixInstancia(ctx context.Context, id int32) (int64, error)
}

var _ Querier = (*Queries)(nil)
