// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zabbix_instancias.sql

package consultas

import (
	"context"
)

const atualizarZabbixInstancia = `-- name: AtualizarZabbixInstancia :one
UPDATE zabbix_instancias
SET nome = $2, url = $3, api_key = $4, atualizado_em = now()
WHERE id = $1
RETURNING id, nome, url, api_key, criado_em, atualizado_em
`

type AtualizarZabbixInstanciaParams struct {
	ID     int32  `json:"id"`
	Nome   string `json:"nome"`
	Url    string `json:"url"`
	ApiKey string `json:"api_key"`
}

func (q *Queries) AtualizarZabbixInstancia(ctx context.Context, arg AtualizarZabbixInstanciaParams) (ZabbixInstancia, error) {
	row := q.db.QueryRow(ctx, atualizarZabbixInstancia,
		arg.ID,
		arg.Nome,
		arg.Url,
		arg.ApiKey,
	)
	var i ZabbixInstancia
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Url,
		&i.ApiKey,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const buscarZabbixInstancia = `-- name: BuscarZabbixInstancia :one
SELECT id, nome, url, api_key, criado_em, atualizado_em FROM zabbix_instancias
WHERE id = $1
`

func (q *Queries) BuscarZabbixInstancia(ctx context.Context, id int32) (ZabbixInstancia, error) {
	row := q.db.QueryRow(ctx, buscarZabbixInstancia, id)
	var i ZabbixInstancia
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Url,
		&i.ApiKey,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const criarZabbixInstancia = `-- name: CriarZabbixInstancia :one

INSERT INTO zabbix_instancias (nome, url, api_key)
VALUES ($1, $2, $3)
RETURNING id, nome, url, api_key, criado_em, atualizado_em
`

type CriarZabbixInstanciaParams struct {
	Nome   string `json:"nome"`
	Url    string `json:"url"`
	ApiKey string `json:"api_key"`
}

// db/queries/zabbix_instancias.sql
//
// Queries do CRUD de instâncias Zabbix. Parâmetros posicionais ($1, $2…)
// — sqlc gera prepared statements, sem concatenação de string.
func (q *Queries) CriarZabbixInstancia(ctx context.Context, arg CriarZabbixInstanciaParams) (ZabbixInstancia, error) {
	row := q.db.QueryRow(ctx, criarZabbixInstancia, arg.Nome, arg.Url, arg.ApiKey)
	var i ZabbixInstancia
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Url,
		&i.ApiKey,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listarZabbixInstancias = `-- name: ListarZabbixInstancias :many
SELECT id, nome, url, api_key, criado_em, atualizado_em FROM zabbix_instancias
ORDER BY id
`

func (q *Queries) ListarZabbixInstancias(ctx context.Context) ([]ZabbixInstancia, error) {
	rows, err := q.db.Query(ctx, listarZabbixInstancias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZabbixInstancia{}
	for rows.Next() {
		var i ZabbixInstancia
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Url,
			&i.ApiKey,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removerZabbixInstancia = `-- name: RemoverZabbixInstancia :execrows
DELETE FROM zabbix_instancias
WHERE id = $1
`

func (q *Queries) RemoverZabbixInstancia(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, removerZabbixInstancia, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
